name: Update

on: push
# on: 
#   schedule:
#     - cron: "30 16 * * *" # 12:30 p.m. EST (4:30 p.m. UTC) every day

jobs:
  update:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.x'
          cache: npm
          DW_TOKEN: ${{ secrets.DW_TOKEN }}

        
      - name: Install packages
        run: npm install node-fetch fs papaparse @actions/core
        
      - name: Run scraper
        run: node app.js 

      - name: Add and commit
        id: add_commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'update csv data and chart metadata'
          committer_name: Automated
          committer_email: ccox@mcclatchydc.com
